import React from 'react';
import { ShieldAlert, AlertTriangle, Scale, BookOpen } from 'lucide-react';

export const TermsPage: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto p-4 sm:p-6 space-y-6 font-sans text-slate-200">
      {/* Header */}
      <div className="bg-command-900 border border-command-800 rounded-lg p-5 shadow">
        <div className="flex items-center space-x-3">
          <div className="p-2 rounded bg-command-800 text-amber-500 border border-command-700">
            <Scale className="w-6 h-6" />
          </div>
          <div>
            <h1 className="text-lg font-bold font-mono text-white tracking-wide">
              TERMS AND OPERATIONAL CONDITIONS
            </h1>
            <p className="text-xs text-slate-400 mt-0.5 font-mono">
              Document Ref: GCVIAS-TOC-2026.1 | Version: 1.4 | Applicable Jurisdiction: Republic of India
            </p>
          </div>
        </div>
      </div>

      {/* Main Legal Content */}
      <div className="bg-command-900 border border-command-800 rounded-lg p-6 space-y-6 text-xs text-slate-300 leading-relaxed">
        <section className="space-y-2">
          <h2 className="font-mono text-sm font-bold text-white uppercase tracking-wider flex items-center space-x-2">
            <BookOpen className="w-4 h-4 text-amber-400" />
            <span>1. Acceptance of Terms & Operational Mandate</span>
          </h2>
          <p>
            By accessing or operating the Geospatial Cyclone Vulnerability and Infrastructure Assessment System (GCVIAS), personnel belonging to State Disaster Management Authorities (SDMAs), District Emergency Operations Centers (DEOCs), line departments, and municipal authorities agree to be bound by these Terms and Operational Conditions. If an operating officer does not accept these terms, access to the command and advisory dispatch features must be ceased immediately.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-mono text-sm font-bold text-white uppercase tracking-wider flex items-center space-x-2">
            <ShieldAlert className="w-4 h-4 text-red-500" />
            <span>2. Statutory Meteorological Authority Disclaimer</span>
          </h2>
          <div className="p-3.5 bg-hazard-severe/10 border border-hazard-severe/30 rounded text-slate-200 space-y-2">
            <p className="font-bold text-red-400 uppercase font-mono">
              IMPORTANT STATUTORY NOTICE REGARDING OFFICIAL BULLETINS:
            </p>
            <p>
              The India Meteorological Department (IMD) is the statutory mandate holder for official weather and cyclonic disturbance forecasting across the Indian territorial waters and landmass. GCVIAS acts exclusively as an analytical downstream tool for spatial exposure modeling and decision support. Nothing generated by GCVIAS shall supersede or invalidate official bulletins, red alerts, or track coordinates issued by the Regional Specialized Meteorological Centre (RSMC) New Delhi.
            </p>
          </div>
        </section>

        <section className="space-y-2">
          <h2 className="font-mono text-sm font-bold text-white uppercase tracking-wider flex items-center space-x-2">
            <AlertTriangle className="w-4 h-4 text-amber-400" />
            <span>3. Nature of Surge & Vulnerability Approximations</span>
          </h2>
          <p>
            Operating officers acknowledge and understand that:
          </p>
          <ul className="list-disc pl-5 space-y-1.5 text-slate-400">
            <li>
              Storm surge polygons and inland infiltration boundaries represent rule-based mathematical approximations derived from pressure deficit, forward velocity, and digital elevation proxies.
            </li>
            <li>
              Output displays illustrate relative risk categorization (Severe, High, Moderate, Low, Monitored) to guide rapid staging of emergency equipment, food rations, and personnel.
            </li>
            <li>
              The system does not claim or provide certified structural engineering structural capacity guarantees for individual structures.
            </li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="font-mono text-sm font-bold text-white uppercase tracking-wider">
            4. Command Responsibility and Dispatch Actions
          </h2>
          <p>
            When an operating officer executes the "Dispatch Advisory" command, the generated evacuation directives, electrical grid isolation notifications, and hospital relocation advisories are logged in statutory audit registries. The decision to enforce mandatory civil evacuation or disconnect 33kV/11kV electrical feeders rests solely with the authorized Incident Commander or District Magistrate in accordance with powers under the Disaster Management Act. GCVIAS and its software maintainers bear no civil liability for operational command decisions executed by local authorities.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-mono text-sm font-bold text-white uppercase tracking-wider">
            5. Degraded Mode & High-Latency Contingency
          </h2>
          <p>
            During extreme weather events, terrestrial fiber-optic networks, cellular towers, and grid power may suffer disruption. Operating personnel are required to maintain secondary battery-backed VHF wireless communication nodes and retain pre-printed offline versions of the infrastructure registry generated via the "Export CSV" facility in GCVIAS.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-mono text-sm font-bold text-white uppercase tracking-wider">
            6. Governing Law & Jurisdiction
          </h2>
          <p>
            These terms are governed by and construed in accordance with the substantive laws of India, including the Information Technology Act and the Disaster Management Act. Any disputes arising from the operational implementation of GCVIAS shall be subject to the exclusive jurisdiction of the competent courts of law in the state of deployment.
          </p>
        </section>
      </div>
    </div>
  );
};
